site_name: My Docs
copyright: "&copy; shunya nakamura"

use_directory_urls: false

theme:
  name: material
  language: ja
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-night
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: "Switch to light mode"

# プラグイン設定
plugins:
  - search:
      lang: "ja"
  - tags:
      tags_file: tags.md

# Markdown拡張機能
markdown_extensions:
  - md_in_html  # HTML内でMarkdownを有効化
  - pymdownx.arithmatex  # 数式サポート
  - attr_list
  - toc
  - meta
  - tables
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

strict: false

# 追加設定
extra:
  generator: false
  search:
    tags: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js

extra_css:
  - css/zunda.css
  - css/table.css
  - css/h2.css
